nsmc:
  ver: with-val
  desc: Naver Sentiment Movie Corpus. Validation set is added. Still, no preprocessing is done. Number of classes are added.
  val_ratio: 0.2
  seed: 1004

tokenizer:
  ver: bpe-nsmc-with-val
  desc: "A BPE tokenizer, trained on nsmc:with-val-1"
  # the symbols to use for special tokens
  pad: <pad>
  unk: <unk>
  bos: <bos>
  eos: <eos>
  vocab_size: 30000


rnn_for_classification:
  ver: cls-nsmc-with-val-overfit
  desc: "A baseline sentiment classifier (hence the `cls` prefix). It is over-fitted to nsmc:with-val."
  max_epochs: 3
  batch_size: 1024
  max_length: 150
  hidden_size: 512
  depth: 2
  shuffle: 1
  lr: 0.0001
  num_classes: 2
