nsmc:
  ver: raw
  desc: Naver Sentiment Movie Corpus. This is the raw version of the corpus. No pre-processing has been done.


tokenizer:
  ver: bpe-nsmc-raw
  desc: "A BPE tokenizer, trained on nsmc:raw"
  # the symbols to use for special tokens
  pad: <pad>
  unk: <unk>
  bos: <bos>
  eos: <eos>
  vocab_size: 30000


rnn:
  ver: cls-nsmc-overfit
  desc: A baseline model. overfitted to the training set.
  batch_size: 64
  shuffle: 1
  max_epochs: 100
  lr: 0.0001
  datamodule: nsmc
  val_ratio: 0.2
  max_length: 150
