nsmc:
  ver: with-val
  desc: Naver Sentiment Movie Corpus. Validation set is added. Still, no preprocessing is done.
  val_ratio: 0.2
  seed: 1004  

tokenizer:
  ver: bpe-nsmc-with-val
  desc: "A BPE tokenizer, trained on nsmc:with-val"
  # the symbols to use for special tokens
  pad: <pad>
  unk: <unk>
  bos: <bos>
  eos: <eos>
  vocab_size: 30000


rnn:
  ver: cls-nsmc-with-val-overfit
  desc: "A baseline model. over-fitted to nsmc:with-val."
  batch_size: 64
  shuffle: 1
  max_epochs: 100
  lr: 0.0001
  datamodule: nsmc
  max_length: 150
